### ISSUE TITLE
Pics 📷

### ISSUE THREAD

**Issue by orta** [alloy/houseboat#5]

**Comment by alloy** [comment]
Here’s the whole set. I’ll have to pick a few for the CP blogpost, if you have suggestions for a few from a fresh outside view, let me know.

https://www.flickr.com/gp/98809276@N08/05pKkf/

**Comment by orta** [comment]
These are :+1:

**Comment by orta** [comment]
Get them in the README

**Comment by alloy** [comment]
Done!

Time to hit the sack now, hasta mañana!!!!11!1!11!!!1
